---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-ui
  namespace: devops
  labels:
    tooltype: jenkins
spec:
  type: LoadBalancer
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ui

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-discovery
  namespace: devops
spec:
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: slaves