---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-ui
  namespace: devops
  labels:
    tooltype: jenkins
spec:
  type: LoadBalancer
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ui

# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: jenkins-discovery
#   namespace: devops
# spec:
#   selector:
#     app: master
#   ports:
#     - protocol: TCP
#       port: 50000
#       targetPort: 50000
#       name: slaves

#Dashboard
---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: dashboard-metrics-scraper
  name: dashboard-metrics-scraper
  namespace: kubernetes-dashboard
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    k8s-app: dashboard-metrics-scraper