---
#### Creating the volume for data persistence
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/jenkins-home/
    
---
##### Creating the volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: jenkins-data
    namespace: devops
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi