##### Creating the volume and volum claim
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-storage
  namespace: devops
provisioner: kubernetes.io/azure-disk
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  storageaccounttype: StandardSSD_LRS
  kind: Managed

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: jenkins-data
    namespace: devops
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: jenkins-storage
    resources:
        requests:
            storage: 30Gi
